webtalk_init -webtalk_dir C:/workspace/ImageProcessing/2x2_Interpolation/2x2_Interpolation.sim/sim_1/behav/xsim/xsim.dir/tb_interpolation_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Jun 27 21:56:06 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "76813392-9b32-40aa-a323-4f8e358dddc8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6fe8718f562a4650b6f00f571cfa59bd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "20" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2904 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "17507780 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "13.39_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14580_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4153044220 -regid "" -xml C:/workspace/ImageProcessing/2x2_Interpolation/2x2_Interpolation.sim/sim_1/behav/xsim/xsim.dir/tb_interpolation_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/workspace/ImageProcessing/2x2_Interpolation/2x2_Interpolation.sim/sim_1/behav/xsim/xsim.dir/tb_interpolation_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/workspace/ImageProcessing/2x2_Interpolation/2x2_Interpolation.sim/sim_1/behav/xsim/xsim.dir/tb_interpolation_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
